"""language-codes

Revision ID: c4bc695ff6b0
Revises: 1160479c1488
Create Date: 2024-03-24 22:03:42.722397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4bc695ff6b0'
down_revision: Union[str, None] = '1160479c1488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_codes',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, primary_key=True),
                    sa.Column('language_code', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_table('language_codes')
    # ### end Alembic commands ###
